### ISSUE TITLE
failed to compile BPF text

### ISSUE THREAD

**Issue by hitzhangjie** [zlim/bcc-docker#6]
Hi, I want to use this docker image to locate the memory leakage in my cgo programme.

When I ran `./memleak -p $pid`, it prints an error stack:

```bash
chdir(/lib/modules/3.10.107-1-tlinux2_kvm_guest-0050/build): No such file or directory
Traceback (most recent call last):
  File "./memleak", line 394, in <module>
    bpf = BPF(text=bpf_source)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 325, in __init__
    raise Exception("Failed to compile BPF text")
Exception: Failed to compile BPF text
```

Could you help solving it?

**Comment by hitzhangjie** [comment]
Does it mean the docker container base image use the kvm packages installed on the host? But I didn't install it on the host.

Maybe. 

the /lib/modules was mounted from the host /lib/modules.
